NAME = server
CLIENT = client

CC		= cc
CFLAGS 	= -Wall -Wextra -Werror -g
INC		= -I./libft/includes
RM		= rm -f
SRCS	= server.c client.c

all: $(NAME)

$(NAME): $(SRCS)
	@make -C ./libft/
	@$(CC) $(CFLAGS) $(INC) -o $(NAME) server.c -Llibft -lft
	@$(CC) $(CFLAGS) $(INC) -o $(CLIENT) client.c -Llibft -lft
	
clean:
	@make clean -C ./libft

fclean: clean
	@make fclean -C ./libft
	@$(RM) $(NAME) $(CLIENT)

re: fclean all

.PHONY: all clean fclean re
